src/OneDrive.js, test/onedrive.test.js
=> fix: check for required arguments clientId and clientSecret

src/OneDrive.js
=> fix(client): set access token correctly

src/OneDrive.d.ts, src/OneDrive.js
=> fix(api): make relpath optional in list children

docs/API.md, package-lock.json, package.json, src/OneDrive.d.ts, src/OneDrive.js
=> feat(auth): add support for interactive login flow

package-lock.json, package.json, src/OneDrive.d.ts, src/OneDrive.js
=> feat(login): provide callback instead of flag

src/OneDrive.js
=> Put should not be set to json

src/OneDrive.js
=> feat(cache): improve token cache

docs/API.md, src/OneDrive.d.ts, src/OneDrive.js
fix #34 
New instance methods for `OneDrive.js`, not sure whether they'd better be grouped in a separate source file.
=> feat(subscription): provide create/delete of subscriptions

package-lock.json, src/OneDrive.d.ts, src/OneDrive.js, src/OneDriveMock.js, src/Table.js, src/Workbook.js, src/Worksheet.js, src/utils.js, test/Table.test.js, test/Workbook.test.js, test/Worksheet.test.js, test/onedrive.test.js
=> feat(onedrive): add support for onedrive uri

src/NamedItemContainer.js, src/OneDrive.js, src/Range.js, src/StatusCodeError.js, src/Table.js, src/Workbook.js, src/Worksheet.js
=> fix(drive): ensure proper error is logged

src/OneDrive.d.ts, src/OneDrive.js, src/OneDriveMock.js, src/fuzzy-helper.js, test/fuzzy-helper.test.js, test/onedrive.test.js
=> feat(onedrive): add support for author friendly file names

src/OneDrive.js, src/StatusCodeError.js, test/statuscodeerror.test.js
=> feat(drive): even better error handling

src/OneDrive.d.ts, src/fuzzy-helper.js, test/fuzzy-helper.test.js, test/onedrive.test.js
=> fix(core): normalize unicode characters

src/OneDrive.d.ts, src/OneDrive.js, src/OneDriveMock.js, test/onedrive.test.js
=> fix(1d): fuzzyGetItem should respect pagination

src/OneDrive.js
=> feat(1d): add filesize

src/OneDrive.js
=> fix(login): set refresh token after device login

package-lock.json, src/OneDrive.js
=> fix(auth): cache.remove.promise is missing

src/OneDrive.js, test/onedrive.test.js
=> fix(fetch): don't assume error is json

package-lock.json, package.json
=> chore(deps): update helix-fetch to 2.1.9

src/NamedItemContainer.js, src/OneDrive.js, src/Table.js
=> fix(onedrive): check response content type before trying to parse JSON

src/OneDrive.js, src/StatusCodeError.js
=> fix: better error report

.mocha-multi.json, .nycrc.json, package-lock.json, package.json, src/OneDrive.d.ts, src/OneDrive.js, src/SharePointSite.js, src/StatusCodeError.js, test/SharePointSite.test.js, test/setup-env.js, test/utils.js
=> feat: add API for SP API

src/OneDrive.js
=> fix: turn 403 in resolve into 404

.nycrc.json, package.json, src/OneDrive.js, test/Table.test.js, test/Workbook.test.js, test/Worksheet.test.js, test/excel.integration.test.js, test/fuzzy-helper.test.js, test/onedrive.test.js, test/statuscodeerror.test.js, test/utils.js
add support to set the `resource` to authenticate against.
=> feat: allow to set authentication resource

src/OneDrive.js, src/SharePointSite.js
=> fix: use http1 for ms access

package-lock.json, package.json, src/OneDrive.d.ts, src/OneDrive.js, test/excel.integration.test.js, test/onedrive.test.js
=> feat: add transparent tenant resolution

src/OneDrive.d.ts, src/OneDrive.js, src/OneDriveMock.js, test/onedrive.test.js
=> feat: speed up fuzzyItem lookup

src/OneDriveMock.js, src/excel/Table.d.ts, src/excel/Table.js, src/excel/Workbook.d.ts, src/excel/Worksheet.d.ts, test/Table.test.js
and properly support `index` in `addColumn`.
required for https://github.com/adobe/helix-indexer/issues/515
=> feat: support delete column

package-lock.json, package.json, src/OneDrive.js, src/OneDriveAuth.js, src/SharePointSite.js, src/StatusCodeError.js, src/cache/S3CachePlugin.js, test/setup-env.js
=> fix: @adobe/helix-fetch -> @adobe/fetch

src/OneDrive.js
=> fix: properly scoped fetch context

src/OneDriveAuth.js
=> fix: OneDriveAuth: properly scoped fetch context

src/OneDrive.js, test/decrypt.js
=> fix: do not log errors that are rethrown

src/OneDriveAuth.js
... otherwise we always call twice.
=> fix: retry only when some account was found

src/OneDrive.js, src/RateLimit.js, src/StatusCodeError.js, src/excel/NamedItemContainer.js, test/RateLimit.test.js, test/onedrive.test.js
related to: https://github.com/adobe/helix-admin/issues/1267
=> feat: add rate limit in log and StatusCodeError

src/OneDrive.js, src/OneDriveAuth.d.ts, src/OneDriveAuth.js, test/onedrive.test.js
=> feat: add log fields for API call logging

src/OneDrive.d.ts, src/OneDrive.js, src/OneDriveMock.js, src/excel/Workbook.d.ts, src/excel/Workbook.js, test/Workbook.test.js, test/fixtures/book.js, test/onedrive.test.js
=> Added Ondrive and excel workbook functionalities

src/OneDriveMock.js, src/excel/Range.d.ts, src/excel/Range.js, test/Worksheet.test.js
=> feat: support insert and delete range operations

src/OneDrive.js, src/OneDriveMock.js, src/excel/Table.d.ts, src/excel/Table.js, src/excel/Workbook.d.ts, src/excel/Workbook.js, test/Table.test.js, test/Workbook.test.js
=> feat: add row at index

src/OneDriveMock.js, src/excel/Table.d.ts, src/excel/Table.js, test/Table.test.js
=> feat: support get range for table

src/OneDrive.js, test/onedrive.test.js
=> fix: better html error

src/OneDrive.js, src/OneDriveAuth.js, test/OneDriveAuth.test.js, test/onedrive.test.js
may be a breaking change (need to check whether clients handle 401 differently)
=> fix: report authenticate failures as 401

src/GraphAPI.d.ts, src/excel/NamedItemContainer.js, src/excel/Range.js, src/excel/Table.js, src/excel/Workbook.js, src/excel/Worksheet.js
Use interface for parent in excel classes, because in the end they just require `doFetch`
=> fix: add interface for doFetch

src/OneDrive.js, test/onedrive.test.js
fixes https://github.com/adobe/helix-admin/issues/2128
=> fix: assert children list contains a value

src/OneDrive.d.ts, src/OneDrive.js, test/onedrive.test.js
see https://learn.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online#how-to-decorate-your-http-traffic
=> feat: allow to set user agent

package-lock.json, package.json, src/OneDriveAuth.js
... and change `instanceof` to `typeof <method> === 'function`
=> fix(deps): change @adobe/helix-shared-tokencache dep to non-fixed
